language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
install:
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"
script:
  - python -mbenchupload --help
  - python -mmetricupload --help
  - mkdir results/
  - python -mpytest --junitxml=results/result.xml tests/tests.py

# Upload the test result with our software
after_success:
   - python -mbenchupload --dir=results
   - python -mmetricupload ./tests/files/example.json
after_failure:
   - python -mbenchupload --dir=results
   - python -mmetricupload ./tests/files/example.json
